from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path, PurePosixPath
from typing import Any, Iterable


class UnsafeArtifactPath(ValueError):
    pass


class ArtifactStore:
    BLOCKED_NAMES = {".env", ".git", "id_rsa", "id_ed25519", "credentials"}

    def __init__(self, workspace: Path) -> None:
        self.workspace = workspace.resolve()
        self.workspace.mkdir(parents=True, exist_ok=True)

    def write_text(self, relative_path: str, content: str) -> Path:
        target = self._safe_target(relative_path)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        return target

    def write_json(self, relative_path: str, payload: Any) -> Path:
        return self.write_text(
            relative_path, json.dumps(payload, ensure_ascii=False, indent=2) + "\n"
        )

    def read_text(self, relative_path: str, max_bytes: int = 200_000) -> str:
        target = self._safe_target(relative_path)
        if not target.is_file():
            raise FileNotFoundError(f"产物不存在：{relative_path}")
        if target.stat().st_size > max_bytes:
            raise ValueError(f"产物超过可读取上限 {max_bytes} bytes")
        return target.read_text(encoding="utf-8", errors="replace")

    def list_files(self, max_files: int = 200) -> list[dict[str, Any]]:
        files: list[dict[str, Any]] = []
        for target in sorted(self.workspace.rglob("*")):
            if not target.is_file():
                continue
            relative = target.relative_to(self.workspace).as_posix()
            try:
                self._safe_target(relative)
            except UnsafeArtifactPath:
                continue
            files.append({"path": relative, "bytes": target.stat().st_size})
            if len(files) >= max_files:
                break
        return files

    def materialize_files(
        self, files: Iterable[dict[str, Any]], prefix: str = "generated"
    ) -> list[Path]:
        written: list[Path] = []
        total_bytes = 0
        for item in files:
            path = str(item.get("path", "")).strip().replace("\\", "/")
            content = str(item.get("content", ""))
            if not path or len(content.encode("utf-8")) > 2_000_000:
                continue
            total_bytes += len(content.encode("utf-8"))
            if total_bytes > 10_000_000:
                raise ValueError("模型生成文件总量超过 10 MB")
            written.append(self.write_text(f"{prefix}/{path}", content))
        return written

    def _safe_target(self, relative_path: str) -> Path:
        posix = PurePosixPath(relative_path.replace("\\", "/"))
        if posix.is_absolute() or not posix.parts:
            raise UnsafeArtifactPath(f"不允许的产物路径：{relative_path}")
        if any(part in {"", ".", ".."} for part in posix.parts):
            raise UnsafeArtifactPath(f"不允许的产物路径：{relative_path}")
        if any(part.lower() in self.BLOCKED_NAMES for part in posix.parts):
            raise UnsafeArtifactPath(f"禁止生成敏感文件：{relative_path}")
        target = self.workspace.joinpath(*posix.parts).resolve()
        if self.workspace not in target.parents:
            raise UnsafeArtifactPath(f"路径越界：{relative_path}")
        return target


def safe_slug(text: str, max_length: int = 50) -> str:
    normalized = re.sub(r"[^\w\u4e00-\u9fff-]+", "-", text.lower()).strip("-")
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()[:8]
    return f"{normalized[:max_length] or 'research'}-{digest}"


def fallback_code_bundle(topic: str) -> dict[str, Any]:
    safe_topic = topic.replace('"""', "").replace("\x00", "")
    experiment = '''"""Deterministic baseline generated by AutoResearch.

Replace `evaluate` with the domain-specific experiment proposed in RESEARCH.md.
"""
from __future__ import annotations

import json
import random
from pathlib import Path


def evaluate(seed: int) -> float:
    random.seed(seed)
    return sum(random.random() for _ in range(1000)) / 1000


def main() -> None:
    scores = [evaluate(seed) for seed in range(5)]
    result = {
        "metric": "baseline_score",
        "mean": sum(scores) / len(scores),
        "scores": scores,
    }
    output = Path("results")
    output.mkdir(exist_ok=True)
    (output / "metrics.json").write_text(json.dumps(result, indent=2), encoding="utf-8")
    print(json.dumps(result))


if __name__ == "__main__":
    main()
'''
    return {
        "files": [
            {
                "path": "README.md",
                "content": f"# Research experiment\n\nTopic: {safe_topic}\n",
            },
            {"path": "experiment.py", "content": experiment},
            {"path": "requirements.txt", "content": ""},
            {
                "path": ".gitignore",
                "content": "data/\nresults/\n__pycache__/\n*.pyc\n.env\n",
            },
        ],
        "experiment": {
            "setup_commands": ["python -m pip install -r requirements.txt"],
            "dataset_commands": [],
            "run_command": "python experiment.py",
            "metrics_file": "results/metrics.json",
        },
    }
